server:
  port: 8080

spring:
  application:
    name: gateway
  profiles:
    active: dev
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://sys-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
          
        - id: user
          uri: lb://user-center
          predicates:
            - Path=/user/**
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yml
        import-check:
          enabled: false
  redis:
    host: localhost
    port: 6379
    timeout: 5s


#    sentinel:
#      transport:
#        dashboard: localhost:9999
#        port: 8719


# Sa-Token配置
sa-token:
  # token名称 (同时也是cookie名称)
  token-name: token
  # token有效期，单位秒，-1代表永不过期
  timeout: 300
  # token临时有效期 (指定时间内无操作就视为token过期)，单位秒
  activity-timeout: -1
  # 是否允许同一账号并发登录 (为false时新登录挤掉旧登录)
  is-concurrent: false
  # 在多人登录同一账号时，是否共用一个token (为false时每次登录新建一个token)
  is-share: false
  # token风格
  token-style: simple-uuid
  # 是否输出操作日志
  is-log: false
  # 是否从cookie中读取token
  is-read-cookie: false
  # 是否从head中读取token
  is-read-header: true
  #jwt密钥
  jwt-secret-key: xiaoerxiaoerbutingbu
  is-write-header: true







